from database.crud import add_genre, add_subgenre, add_characteristic

def seed_reference_data():
    # Add some initial characteristics to the characteristics table
    add_characteristic("Violence")
    add_characteristic("Gore")
    add_characteristic("Horror")
    add_characteristic("Dark")
    add_characteristic("Psychological")
    add_characteristic("Thriller")
    add_characteristic("Mystery")
    add_characteristic("Suspense")
    add_characteristic("Crime")
    add_characteristic("Detective")
    add_characteristic("Supernatural")
    add_characteristic("Paranormal")
    add_characteristic("Occult")
    add_characteristic("Dystopian")
    add_characteristic("Post-Apocalyptic")
    add_characteristic("Science Fiction")
    add_characteristic("Fantasy")

    # Add some initial genres to the genres table  
    art_id = add_genre('Art')
    biography_id = add_genre('Biography')
    business_id = add_genre('Business')
    computing_id = add_genre('Computing & Technology')
    cooking_id = add_genre('Cooking')
    education_id = add_genre('Education')
    environment_id = add_genre('Environment & Nature')
    essays_id = add_genre('Essays')
    fashion_id = add_genre('Fashion')
    health_id = add_genre('Health & Medicine')
    history_id = add_genre('History')
    hobbies_id = add_genre('Hobbies & Crafts')
    horror_id = add_genre('Horror')
    humour_id = add_genre('Humour')
    linguistics_id = add_genre('Linguistics')
    literature_id = add_genre('Literature')
    mathematics_id = add_genre('Mathematics')
    music_id = add_genre('Music')
    mythology_id = add_genre('Mythology')
    philosophy_id = add_genre('Philosophy')
    psychology_id = add_genre('Psychology')
    religion_id = add_genre('Religion & Spirituality')
    romance_id = add_genre('Romance')
    science_id = add_genre('Science')
    scifi_id = add_genre('Science Fiction')
    selfhelp_id = add_genre('Self-Help')
    sociology_id = add_genre('Sociology')
    sports_id = add_genre('Sports')
    travel_id = add_genre('Travel')
    truecrime_id = add_genre('True Crime')
    fantasy_id = add_genre('Fantasy')
    mystery_id = add_genre('Mystery & Thriller')




    # Add some initial subgenres to the subgenres table
    # Art subgenres
    add_subgenre(art_id, 'Art History')
    add_subgenre(art_id, 'Art Theory')
    add_subgenre(art_id, 'Fine Art')
    add_subgenre(art_id, 'Painting')
    add_subgenre(art_id, 'Drawing')
    add_subgenre(art_id, 'Sculpture')
    add_subgenre(art_id, 'Photography')
    add_subgenre(art_id, 'Printmaking')
    add_subgenre(art_id, 'Illustration')
    add_subgenre(art_id, 'Graphic Design')
    add_subgenre(art_id, 'Architecture')
    add_subgenre(art_id, 'Art Criticism')
    add_subgenre(art_id, 'Modern Art')
    add_subgenre(art_id, 'Contemporary Art')
    add_subgenre(art_id, 'Renaissance Art')
    add_subgenre(art_id, 'Classical Art')
    add_subgenre(art_id, 'Digital Art')

    # Biography subgenres
    add_subgenre(biography_id, 'Autobiography')
    add_subgenre(biography_id, 'Memoir')
    add_subgenre(biography_id, 'Celebrity Biography')
    add_subgenre(biography_id, 'Political Biography')
    add_subgenre(biography_id, 'Artist Biography')
    add_subgenre(biography_id, 'Writer Biography')
    add_subgenre(biography_id, 'Historical Biography')
    add_subgenre(biography_id, 'Scientific Biography')
    add_subgenre(biography_id, 'Musician Biography')
    add_subgenre(biography_id, 'Royal Biography')
    add_subgenre(biography_id, 'Military Biography')
    add_subgenre(biography_id, 'Literary Biography')

    # Business subgenres
    add_subgenre(business_id, 'Entrepreneurship')
    add_subgenre(business_id, 'Management')
    add_subgenre(business_id, 'Leadership')
    add_subgenre(business_id, 'Marketing')
    add_subgenre(business_id, 'Finance')
    add_subgenre(business_id, 'Investing')
    add_subgenre(business_id, 'Economics')
    add_subgenre(business_id, 'Business Strategy')
    add_subgenre(business_id, 'Startups')
    add_subgenre(business_id, 'Personal Finance')
    add_subgenre(business_id, 'Corporate Finance')
    add_subgenre(business_id, 'Human Resources')
    add_subgenre(business_id, 'Negotiation')
    add_subgenre(business_id, 'Sales')
    add_subgenre(business_id, 'Productivity')

    # Computing & Technology subgenres
    add_subgenre(computing_id, 'Programming')
    add_subgenre(computing_id, 'Software Engineering')
    add_subgenre(computing_id, 'Computer Science')
    add_subgenre(computing_id, 'Artificial Intelligence')
    add_subgenre(computing_id, 'Machine Learning')
    add_subgenre(computing_id, 'Data Science')
    add_subgenre(computing_id, 'Data Engineering')
    add_subgenre(computing_id, 'Cybersecurity')
    add_subgenre(computing_id, 'Databases')
    add_subgenre(computing_id, 'Web Development')
    add_subgenre(computing_id, 'Game Development')
    add_subgenre(computing_id, 'Computer Networks')
    add_subgenre(computing_id, 'Operating Systems')
    add_subgenre(computing_id, 'Algorithms')
    add_subgenre(computing_id, 'Information Technology')

    # Cooking subgenres
    add_subgenre(cooking_id, 'Baking')
    add_subgenre(cooking_id, 'Desserts')
    add_subgenre(cooking_id, 'Vegetarian Cooking')
    add_subgenre(cooking_id, 'Vegan Cooking')
    add_subgenre(cooking_id, 'International Cuisine')
    add_subgenre(cooking_id, 'Italian Cuisine')
    add_subgenre(cooking_id, 'French Cuisine')
    add_subgenre(cooking_id, 'Asian Cuisine')
    add_subgenre(cooking_id, 'Japanese Cuisine')
    add_subgenre(cooking_id, 'Indian Cuisine')
    add_subgenre(cooking_id, 'Mediterranean Cuisine')
    add_subgenre(cooking_id, 'Healthy Cooking')
    add_subgenre(cooking_id, 'Quick Meals')
    add_subgenre(cooking_id, 'Bread')
    add_subgenre(cooking_id, 'Pastry')

    # Education subgenres
    add_subgenre(education_id, 'Teaching')
    add_subgenre(education_id, 'Pedagogy')
    add_subgenre(education_id, 'Educational Psychology')
    add_subgenre(education_id, 'Learning Theory')
    add_subgenre(education_id, 'Higher Education')
    add_subgenre(education_id, 'Primary Education')
    add_subgenre(education_id, 'Secondary Education')
    add_subgenre(education_id, 'Special Education')
    add_subgenre(education_id, 'Homeschooling')
    add_subgenre(education_id, 'Study Skills')

    # Environment & Nature subgenres
    add_subgenre(environment_id, 'Ecology')
    add_subgenre(environment_id, 'Conservation')
    add_subgenre(environment_id, 'Climate Change')
    add_subgenre(environment_id, 'Natural History')
    add_subgenre(environment_id, 'Wildlife')
    add_subgenre(environment_id, 'Botany')
    add_subgenre(environment_id, 'Zoology')
    add_subgenre(environment_id, 'Marine Biology')
    add_subgenre(environment_id, 'Environmentalism')
    add_subgenre(environment_id, 'Sustainability')
    add_subgenre(environment_id, 'Nature Writing')

    # Essays
    add_subgenre(essays_id, 'Literary Essays')
    add_subgenre(essays_id, 'Philosophical Essays')
    add_subgenre(essays_id, 'Political Essays')
    add_subgenre(essays_id, 'Cultural Essays')
    add_subgenre(essays_id, 'Personal Essays')
    add_subgenre(essays_id, 'Critical Essays')
    add_subgenre(essays_id, 'Scientific Essays')
    add_subgenre(essays_id, 'Social Commentary')

    # Fashion subgenres
    add_subgenre(fashion_id, 'Fashion History')
    add_subgenre(fashion_id, 'Fashion Design')
    add_subgenre(fashion_id, 'Textiles')
    add_subgenre(fashion_id, 'Costume')
    add_subgenre(fashion_id, 'Fashion Photography')
    add_subgenre(fashion_id, 'Street Fashion')
    add_subgenre(fashion_id, 'Fashion Theory')

    # Horror subgenres
    add_subgenre(horror_id, 'Psychological Horror')
    add_subgenre(horror_id, 'Gothic Horror')
    add_subgenre(horror_id, 'Cosmic Horror')
    add_subgenre(horror_id, 'Lovecraftian Horror')
    add_subgenre(horror_id, 'Body Horror')
    add_subgenre(horror_id, 'Folk Horror')
    add_subgenre(horror_id, 'Supernatural Horror')
    add_subgenre(horror_id, 'Occult Horror')
    add_subgenre(horror_id, 'Religious Horror')
    add_subgenre(horror_id, 'Creature Horror')
    add_subgenre(horror_id, 'Monster Horror')
    add_subgenre(horror_id, 'Paranormal Horror')
    add_subgenre(horror_id, 'Haunted House')
    add_subgenre(horror_id, 'Extreme Horror')
    add_subgenre(horror_id, 'Splatterpunk')
    add_subgenre(horror_id, 'Splatter Horror')
    add_subgenre(horror_id, 'Erotic Horror')
    add_subgenre(horror_id, 'Weird Horror')
    add_subgenre(horror_id, 'Surreal Horror')
    add_subgenre(horror_id, 'Apocalyptic Horror')
    add_subgenre(horror_id, 'Post-Apocalyptic Horror')
    add_subgenre(horror_id, 'Eco-Horror')
    add_subgenre(horror_id, 'Science Fiction Horror')
    add_subgenre(horror_id, 'Dark Fantasy Horror')
    add_subgenre(horror_id, 'Psychological Thriller')

    # Humour subgenres
    add_subgenre(humour_id, 'Satire')
    add_subgenre(humour_id, 'Dark Humour')
    add_subgenre(humour_id, 'Absurdist Humour')
    add_subgenre(humour_id, 'Parody')
    add_subgenre(humour_id, 'Political Humour')
    add_subgenre(humour_id, 'Black Comedy')
    add_subgenre(humour_id, 'Observational Humour')
    add_subgenre(humour_id, 'Surreal Humour')
    add_subgenre(humour_id, 'Slapstick')
    add_subgenre(humour_id, 'Comic Fiction')

    # Linguistics subgenres
    add_subgenre(linguistics_id, 'Language History')
    add_subgenre(linguistics_id, 'Sociolinguistics')
    add_subgenre(linguistics_id, 'Psycholinguistics')
    add_subgenre(linguistics_id, 'Phonetics')
    add_subgenre(linguistics_id, 'Phonology')
    add_subgenre(linguistics_id, 'Syntax')
    add_subgenre(linguistics_id, 'Semantics')
    add_subgenre(linguistics_id, 'Pragmatics')
    add_subgenre(linguistics_id, 'Morphology')
    add_subgenre(linguistics_id, 'Historical Linguistics')
    add_subgenre(linguistics_id, 'Language Acquisition')
    add_subgenre(linguistics_id, 'Translation')
    add_subgenre(linguistics_id, 'Writing Systems')

    # Literature subgenres
    add_subgenre(literature_id, 'Literary Fiction')
    add_subgenre(literature_id, 'Classic Literature')
    add_subgenre(literature_id, 'Modern Literature')
    add_subgenre(literature_id, 'Contemporary Literature')
    add_subgenre(literature_id, 'Experimental Fiction')
    add_subgenre(literature_id, 'Philosophical Fiction')
    add_subgenre(literature_id, 'Psychological Fiction')
    add_subgenre(literature_id, 'Existential Fiction')
    add_subgenre(literature_id, 'Absurdist Fiction')
    add_subgenre(literature_id, 'Surreal Fiction')
    add_subgenre(literature_id, 'Weird Fiction')
    add_subgenre(literature_id, 'New Weird')
    add_subgenre(literature_id, 'Speculative Fiction')
    add_subgenre(literature_id, 'Magical Realism')
    add_subgenre(literature_id, 'Slipstream')
    add_subgenre(literature_id, 'Bizarro Fiction')
    add_subgenre(literature_id, 'Dreamlike Fiction')

    # Mathematics subgenres
    add_subgenre(mathematics_id, 'Pure Mathematics')
    add_subgenre(mathematics_id, 'Applied Mathematics')
    add_subgenre(mathematics_id, 'Number Theory')
    add_subgenre(mathematics_id, 'Algebra')
    add_subgenre(mathematics_id, 'Geometry')
    add_subgenre(mathematics_id, 'Topology')
    add_subgenre(mathematics_id, 'Calculus')
    add_subgenre(mathematics_id, 'Statistics')
    add_subgenre(mathematics_id, 'Probability')
    add_subgenre(mathematics_id, 'Discrete Mathematics')
    add_subgenre(mathematics_id, 'Mathematical Logic')
    add_subgenre(mathematics_id, 'Mathematical Physics')

    # Music subgenres
    add_subgenre(music_id, 'Music Theory')
    add_subgenre(music_id, 'Music History')
    add_subgenre(music_id, 'Musicology')
    add_subgenre(music_id, 'Composition')
    add_subgenre(music_id, 'Performance')
    add_subgenre(music_id, 'Classical Music')
    add_subgenre(music_id, 'Jazz')
    add_subgenre(music_id, 'Rock')
    add_subgenre(music_id, 'Electronic Music')
    add_subgenre(music_id, 'Folk Music')
    add_subgenre(music_id, 'Opera')
    add_subgenre(music_id, 'Music Biography')
    add_subgenre(music_id, 'Sheet Music')

    # Mythology subgenres
    add_subgenre(mythology_id, 'Greek Mythology')
    add_subgenre(mythology_id, 'Roman Mythology')
    add_subgenre(mythology_id, 'Norse Mythology')
    add_subgenre(mythology_id, 'Egyptian Mythology')
    add_subgenre(mythology_id, 'Celtic Mythology')
    add_subgenre(mythology_id, 'Slavic Mythology')
    add_subgenre(mythology_id, 'Mesopotamian Mythology')
    add_subgenre(mythology_id, 'Japanese Mythology')
    add_subgenre(mythology_id, 'Chinese Mythology')
    add_subgenre(mythology_id, 'Hindu Mythology')
    add_subgenre(mythology_id, 'Mesoamerican Mythology')
    add_subgenre(mythology_id, 'African Mythology')
    add_subgenre(mythology_id, 'Polynesian Mythology')
    add_subgenre(mythology_id, 'Native American Mythology')
    add_subgenre(mythology_id, 'Folklore')
    add_subgenre(mythology_id, 'Fairy Tales')
    add_subgenre(mythology_id, 'Legends')

    # Philosophy subgenres
    add_subgenre(philosophy_id, 'Ethics')
    add_subgenre(philosophy_id, 'Metaphysics')
    add_subgenre(philosophy_id, 'Epistemology')
    add_subgenre(philosophy_id, 'Logic')
    add_subgenre(philosophy_id, 'Existentialism')
    add_subgenre(philosophy_id, 'Absurdism')
    add_subgenre(philosophy_id, 'Phenomenology')
    add_subgenre(philosophy_id, 'Political Philosophy')
    add_subgenre(philosophy_id, 'Philosophy of Mind')
    add_subgenre(philosophy_id, 'Philosophy of Science')
    add_subgenre(philosophy_id, 'Philosophy of Language')
    add_subgenre(philosophy_id, 'Aesthetics')
    add_subgenre(philosophy_id, 'Stoicism')
    add_subgenre(philosophy_id, 'Nihilism')
    add_subgenre(philosophy_id, 'Eastern Philosophy')
    add_subgenre(philosophy_id, 'Ancient Philosophy')
    add_subgenre(philosophy_id, 'Medieval Philosophy')
    add_subgenre(philosophy_id, 'Modern Philosophy')
    add_subgenre(philosophy_id, 'Continental Philosophy')
    add_subgenre(philosophy_id, 'Analytic Philosophy')
    add_subgenre(philosophy_id, 'Philosophy of Religion')
    add_subgenre(philosophy_id, 'Philosophy of Mathematics')

    # Psychology subgenres
    add_subgenre(psychology_id, 'Clinical Psychology')
    add_subgenre(psychology_id, 'Cognitive Psychology')
    add_subgenre(psychology_id, 'Social Psychology')
    add_subgenre(psychology_id, 'Developmental Psychology')
    add_subgenre(psychology_id, 'Behavioural Psychology')
    add_subgenre(psychology_id, 'Personality Psychology')
    add_subgenre(psychology_id, 'Evolutionary Psychology')
    add_subgenre(psychology_id, 'Neuroscience')
    add_subgenre(psychology_id, 'Psychopathology')
    add_subgenre(psychology_id, 'Psychoanalysis')
    add_subgenre(psychology_id, 'Positive Psychology')
    add_subgenre(psychology_id, 'Industrial Psychology')
    add_subgenre(psychology_id, 'Educational Psychology')

    # Religion & Spirituality subgenres
    add_subgenre(religion_id, 'Christianity')
    add_subgenre(religion_id, 'Catholicism')
    add_subgenre(religion_id, 'Orthodoxy')
    add_subgenre(religion_id, 'Protestantism')
    add_subgenre(religion_id, 'Islam')
    add_subgenre(religion_id, 'Judaism')
    add_subgenre(religion_id, 'Hinduism')
    add_subgenre(religion_id, 'Buddhism')
    add_subgenre(religion_id, 'Taoism')
    add_subgenre(religion_id, 'Shinto')
    add_subgenre(religion_id, 'Paganism')
    add_subgenre(religion_id, 'Occultism')
    add_subgenre(religion_id, 'Mysticism')
    add_subgenre(religion_id, 'Esotericism')
    add_subgenre(religion_id, 'Comparative Religion')
    add_subgenre(religion_id, 'Theology')
    add_subgenre(religion_id, 'Religious History')
    add_subgenre(religion_id, 'Spirituality')

    # Romance subgenres
    add_subgenre(romance_id, 'Contemporary Romance')
    add_subgenre(romance_id, 'Historical Romance')
    add_subgenre(romance_id, 'Fantasy Romance')
    add_subgenre(romance_id, 'Paranormal Romance')
    add_subgenre(romance_id, 'Dark Romance')
    add_subgenre(romance_id, 'Erotic Romance')
    add_subgenre(romance_id, 'Gothic Romance')
    add_subgenre(romance_id, 'Romantic Suspense')
    add_subgenre(romance_id, 'Romantic Fantasy')
    add_subgenre(romance_id, 'Science Fiction Romance')
    add_subgenre(romance_id, 'Post-Apocalyptic Romance')
    add_subgenre(romance_id, 'Dystopian Romance')
    add_subgenre(romance_id, 'Forbidden Romance')
    add_subgenre(romance_id, 'Monster Romance')
    add_subgenre(romance_id, 'Alien Romance')
    add_subgenre(romance_id, 'Shifter Romance')
    add_subgenre(romance_id, 'Vampire Romance')
    add_subgenre(romance_id, 'Demon Romance')
    add_subgenre(romance_id, 'Fae Romance')
    add_subgenre(romance_id, 'Supernatural Romance')

    # Science subgenres
    add_subgenre(science_id, 'Physics')
    add_subgenre(science_id, 'Chemistry')
    add_subgenre(science_id, 'Biology')
    add_subgenre(science_id, 'Astronomy')
    add_subgenre(science_id, 'Astrophysics')
    add_subgenre(science_id, 'Geology')
    add_subgenre(science_id, 'Earth Science')
    add_subgenre(science_id, 'Environmental Science')
    add_subgenre(science_id, 'Neuroscience')
    add_subgenre(science_id, 'Medicine')
    add_subgenre(science_id, 'Genetics')
    add_subgenre(science_id, 'Evolution')
    add_subgenre(science_id, 'Microbiology')
    add_subgenre(science_id, 'Biochemistry')
    add_subgenre(science_id, 'Quantum Physics')
    add_subgenre(science_id, 'Cosmology')

    # Science Fiction subgenres
    add_subgenre(scifi_id, 'Hard Science Fiction')
    add_subgenre(scifi_id, 'Soft Science Fiction')
    add_subgenre(scifi_id, 'Space Opera')
    add_subgenre(scifi_id, 'Cyberpunk')
    add_subgenre(scifi_id, 'Steampunk')
    add_subgenre(scifi_id, 'Biopunk')
    add_subgenre(scifi_id, 'Solarpunk')
    add_subgenre(scifi_id, 'Dystopian')
    add_subgenre(scifi_id, 'Post-Apocalyptic')
    add_subgenre(scifi_id, 'Time Travel')
    add_subgenre(scifi_id, 'Alternate History')
    add_subgenre(scifi_id, 'First Contact')
    add_subgenre(scifi_id, 'Alien')
    add_subgenre(scifi_id, 'Extraterrestrial')
    add_subgenre(scifi_id, 'Genetic Engineering')
    add_subgenre(scifi_id, 'Artificial Intelligence')
    add_subgenre(scifi_id, 'Climate Fiction')
    add_subgenre(scifi_id, 'Science Fiction Horror')
    add_subgenre(scifi_id, 'Science Fiction Romance')
    add_subgenre(scifi_id, 'Military Science Fiction')

    # Self-Help subgenres
    add_subgenre(selfhelp_id, 'Personal Development')
    add_subgenre(selfhelp_id, 'Productivity')
    add_subgenre(selfhelp_id, 'Motivation')
    add_subgenre(selfhelp_id, 'Habits')
    add_subgenre(selfhelp_id, 'Relationships')
    add_subgenre(selfhelp_id, 'Communication')
    add_subgenre(selfhelp_id, 'Career')
    add_subgenre(selfhelp_id, 'Finance')
    add_subgenre(selfhelp_id, 'Leadership')
    add_subgenre(selfhelp_id, 'Mindfulness')
    add_subgenre(selfhelp_id, 'Spiritual Growth')
    add_subgenre(selfhelp_id, 'Philosophy')
    add_subgenre(selfhelp_id, 'Psychology')

    # Sociology subgenres
    add_subgenre(sociology_id, 'Social Theory')
    add_subgenre(sociology_id, 'Culture')
    add_subgenre(sociology_id, 'Gender Studies')
    add_subgenre(sociology_id, 'Family Studies')
    add_subgenre(sociology_id, 'Social Psychology')
    add_subgenre(sociology_id, 'Class')
    add_subgenre(sociology_id, 'Social Inequality')
    add_subgenre(sociology_id, 'Demography')
    add_subgenre(sociology_id, 'Urban Sociology')
    add_subgenre(sociology_id, 'Rural Sociology')
    add_subgenre(sociology_id, 'Political Sociology')
    add_subgenre(sociology_id, 'Sociology of Religion')

    # Sports subgenres
    add_subgenre(sports_id, 'Yoga')
    add_subgenre(sports_id, 'Meditation')
    add_subgenre(sports_id, 'Weight Training')
    add_subgenre(sports_id, 'Fitness')
    add_subgenre(sports_id, 'Chess')

    # Travel subgenres
    add_subgenre(travel_id, 'Travel Writing')
    add_subgenre(travel_id, 'Travel Memoir')
    add_subgenre(travel_id, 'Guidebook')
    add_subgenre(travel_id, 'Adventure Travel')
    add_subgenre(travel_id, 'Backpacking')
    add_subgenre(travel_id, 'Cultural Travel')  
    add_subgenre(travel_id, 'Food Travel')
    add_subgenre(travel_id, 'Nature Travel')
    add_subgenre(travel_id, 'History & Travel')

    # True Crime subgenres
    add_subgenre(truecrime_id, 'Murder')
    add_subgenre(truecrime_id, 'Serial Killers')
    add_subgenre(truecrime_id, 'Organised Crime')
    add_subgenre(truecrime_id, 'Forensic Investigation')
    add_subgenre(truecrime_id, 'Criminal Psychology')
    add_subgenre(truecrime_id, 'Cold Cases')
    add_subgenre(truecrime_id, 'Missing Persons')
    add_subgenre(truecrime_id, 'Historical Crime')
    add_subgenre(truecrime_id, 'True Crime Memoir')
    add_subgenre(truecrime_id, 'Legal Investigation')

    # Fantasy subgenres
    add_subgenre(fantasy_id, 'High Fantasy')
    add_subgenre(fantasy_id, 'Epic Fantasy')
    add_subgenre(fantasy_id, 'Dark Fantasy')
    add_subgenre(fantasy_id, 'Urban Fantasy')
    add_subgenre(fantasy_id, 'Low Fantasy')
    add_subgenre(fantasy_id, 'Historical Fantasy')
    add_subgenre(fantasy_id, 'Portal Fantasy')
    add_subgenre(fantasy_id, 'Fairy Tale Retelling')
    add_subgenre(fantasy_id, 'Grimdark')
    add_subgenre(fantasy_id, 'Sword & Sorcery')
    add_subgenre(fantasy_id, 'Mythic Fantasy')
    add_subgenre(fantasy_id, 'Cozy Fantasy')
    add_subgenre(fantasy_id, 'Romantic Fantasy')
    add_subgenre(fantasy_id, 'Fantasy Horror')
    add_subgenre(fantasy_id, 'Monster Fantasy')
    add_subgenre(fantasy_id, 'Folk Fantasy')
    add_subgenre(fantasy_id, 'Weird Fantasy')

    # Mystery & Thriller subgenres
    add_subgenre(mystery_id, 'Mystery')
    add_subgenre(mystery_id, 'Crime Fiction')
    add_subgenre(mystery_id, 'Detective Fiction')
    add_subgenre(mystery_id, 'Cozy Mystery')
    add_subgenre(mystery_id, 'Police Procedural')
    add_subgenre(mystery_id, 'Psychological Thriller')
    add_subgenre(mystery_id, 'Domestic Thriller')
    add_subgenre(mystery_id, 'Legal Thriller')
    add_subgenre(mystery_id, 'Political Thriller')
    add_subgenre(mystery_id, 'Espionage Thriller')
    add_subgenre(mystery_id, 'Techno-Thriller')
    add_subgenre(mystery_id, 'Historical Mystery')
    add_subgenre(mystery_id, 'Historical Thriller')
    add_subgenre(mystery_id, 'Noir')
    add_subgenre(mystery_id, 'Hardboiled')
    add_subgenre(mystery_id, 'Locked-Room Mystery')
    add_subgenre(mystery_id, 'Suspense')


    # Add some initial characteristics to the characteristics table
    # Atmosphere / tone
    add_characteristic("Dark")
    add_characteristic("Bleak")
    add_characteristic("Gloomy")
    add_characteristic("Melancholic")
    add_characteristic("Haunting")
    add_characteristic("Eerie")
    add_characteristic("Unsettling")
    add_characteristic("Creepy")
    add_characteristic("Disturbing")
    add_characteristic("Nightmarish")
    add_characteristic("Atmospheric")
    add_characteristic("Moody")
    add_characteristic("Tense")
    add_characteristic("Suspenseful")
    add_characteristic("Claustrophobic")
    add_characteristic("Dreamlike")
    add_characteristic("Surreal")
    add_characteristic("Absurd")
    add_characteristic("Whimsical")
    add_characteristic("Cozy")
    add_characteristic("Heartwarming")
    add_characteristic("Feel-Good")
    add_characteristic("Hopeful")
    add_characteristic("Bittersweet")
    add_characteristic("Nostalgic")
    add_characteristic("Humorous")
    add_characteristic("Satirical")

    # Themes / ideas
    add_characteristic("Philosophical")
    add_characteristic("Existential")
    add_characteristic("Absurdist")
    add_characteristic("Psychological")
    add_characteristic("Introspective")
    add_characteristic("Metaphysical")
    add_characteristic("Ethical")
    add_characteristic("Political")
    add_characteristic("Social Commentary")
    add_characteristic("Religious")
    add_characteristic("Spiritual")
    add_characteristic("Mythological")
    add_characteristic("Folkloric")
    add_characteristic("Historical")
    add_characteristic("Feminist")
    add_characteristic("Classical")
    add_characteristic("Literary")
    add_characteristic("Experimental")

    # Horror / disturbing content
    add_characteristic("Gore")
    add_characteristic("Extreme Gore")
    add_characteristic("Graphic Violence")
    add_characteristic("Death")
    add_characteristic("Murder")
    add_characteristic("Torture")
    add_characteristic("Cannibalism")
    add_characteristic("Dismemberment")
    add_characteristic("Blood")
    add_characteristic("Monster")
    add_characteristic("Creature")
    add_characteristic("Paranormal")
    add_characteristic("Supernatural")
    add_characteristic("Occult")
    add_characteristic("Demon")
    add_characteristic("Ghost")
    add_characteristic("Possession")
    add_characteristic("Witchcraft")
    add_characteristic("Cosmic")
    add_characteristic("Lovecraftian")
    add_characteristic("Apocalyptic")

    # Romance / sexuality
    add_characteristic("Erotic")
    add_characteristic("Explicit")
    add_characteristic("Sexual")
    add_characteristic("Sensual")
    add_characteristic("Forbidden Love")
    add_characteristic("Obsessive Love")
    add_characteristic("Possessive")
    add_characteristic("Jealousy")
    add_characteristic("Power Imbalance")
    add_characteristic("Enemies to Lovers")
    add_characteristic("Slow Burn")
    add_characteristic("Forced Proximity")
    add_characteristic("Stockholm Syndrome")

    # Characters / creatures
    add_characteristic("Alien")
    add_characteristic("Non-Human")
    add_characteristic("Vampire")
    add_characteristic("Werewolf")
    add_characteristic("Shifter")
    add_characteristic("Demon")
    add_characteristic("Fae")
    add_characteristic("Orc")
    add_characteristic("Robot")
    add_characteristic("Artificial Intelligence")
    add_characteristic("Supernatural Being")

    # Setting / world
    add_characteristic("Medieval")
    add_characteristic("Ancient World")
    add_characteristic("Victorian")
    add_characteristic("Historical")
    add_characteristic("Rural")
    add_characteristic("Small Town")
    add_characteristic("Urban")
    add_characteristic("Isolated")
    add_characteristic("Wilderness")
    add_characteristic("Space")
    add_characteristic("Alien World")
    add_characteristic("Post-Apocalyptic")
    add_characteristic("Dystopian")
    add_characteristic("Alternate Reality")
    add_characteristic("Otherworldly")

    # Style / reading experience
    add_characteristic("Fast-Paced")
    add_characteristic("Slow-Paced")
    add_characteristic("Character-Driven")
    add_characteristic("Plot-Driven")
    add_characteristic("World-Building")
    add_characteristic("Dialogue-Heavy")
    add_characteristic("Descriptive")
    add_characteristic("Minimalist")
    add_characteristic("Experimental")
    add_characteristic("Nonlinear")
    add_characteristic("Multiple Perspectives")
    add_characteristic("Unreliable Narrator")
    add_characteristic("First Person")
    add_characteristic("Second Person")
    add_characteristic("Third Person")
    add_characteristic("Stream of Consciousness")

    # Content / structure
    add_characteristic("Anthological")
    add_characteristic("Episodic")
    add_characteristic("Short Stories")
    add_characteristic("Multiple Timelines")
    add_characteristic("Multiple Generations")
    add_characteristic("Coming of Age")
    add_characteristic("Quest")
    add_characteristic("Survival")
    add_characteristic("Mystery")
    add_characteristic("Investigation")
    add_characteristic("Journey")
    add_characteristic("Revenge")
    add_characteristic("Tragedy")


if __name__ == "__main__":
    seed_reference_data()